import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function maskSensitivePrompt(prompt) {
  if (typeof prompt !== "string") {
    return "";
  }

  let masked = prompt;

  masked = masked.replace(
    /-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----/gi,
    "[REDACTED_PRIVATE_KEY]"
  );

  masked = masked.replace(
    /\b(?:mongodb(?:\+srv)?|postgres(?:ql)?|mysql|mssql):\/\/[^\s"'<>]+/gi,
    "[REDACTED_DATABASE_URL]"
  );

  masked = masked.replace(
    /\b(?:api[_-]?key|apikey|api[_-]?token)\s*[:=]\s*["']?[A-Za-z0-9_\-]{16,}["']?/gi,
    "[REDACTED_API_KEY]"
  );

  masked = masked.replace(
    /\bAKIA[0-9A-Z]{16}\b/gi,
    "[REDACTED_AWS_KEY]"
  );

  masked = masked.replace(
    /\beyJ[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,}\b/g,
    "[REDACTED_JWT]"
  );

  masked = masked.replace(
    /\b(?:access[_-]?token|auth[_-]?token|secret[_-]?token)\s*(?::|=|\bis\b)\s*["']?[^\s"',;]+["']?/gi,
    "[REDACTED_TOKEN]"
  );

  masked = masked.replace(
    /\b(?:password|passwd|pwd|passcode)\s*(?::|=|\bis\b)\s*["']?[^\s"',;]+["']?/gi,
    "[REDACTED_PASSWORD]"
  );

  masked = masked.replace(
    /\b(?:secret|client[_-]?secret|private[_-]?token)\s*[:=]\s*["']?[^\s"',;]+["']?/gi,
    "[REDACTED_SECRET]"
  );

  masked = masked.replace(
    /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,
    "[REDACTED_EMAIL]"
  );

  masked = masked.replace(
    /\b(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)){3}\b/g,
    "[REDACTED_IP]"
  );

  masked = masked.replace(
    /(?<!\d)(?:\+?\d{1,3}[\s.-]?)?(?:\d{3}[\s.-]?\d{3}[\s.-]?\d{4}|\d{10})(?!\d)/g,
    "[REDACTED_PHONE]"
  );

  return masked;
}

export const generateHistoryReport = (user, history) => {
  const doc = new jsPDF();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(0, 153, 255);
  doc.text("PromptSentinel", 14, 20);

  doc.setFontSize(14);
  doc.setTextColor(80);
  doc.text("Prompt Scan History Report", 14, 30);

  doc.setDrawColor(0, 153, 255);
  doc.line(14, 35, 196, 35);

  doc.setFontSize(15);
  doc.setTextColor(0);

  doc.text("User Information", 14, 48);

  doc.setFontSize(11);

  doc.text(`Name : ${user.fullName}`, 18, 58);
  doc.text(`Email : ${user.email}`, 18, 66);
  doc.text(`Role : ${user.role}`, 18, 74);

  doc.text(
    `Generated : ${new Date().toLocaleString()}`,
    18,
    82
  );

  autoTable(doc, {
    startY: 92,

    head: [[
      "Prompt",
      "Threat",
      "Attack Type",
      "Risk",
      "Confidence",
      "Date"
    ]],

    body: history.map((scan) => [
      maskSensitivePrompt(scan.prompt) || "Prompt unavailable",
      scan.threatLevel,
      scan.attackType,
      `${scan.riskScore}/100`,
      `${scan.confidence}%`,
      new Date(scan.createdAt).toLocaleDateString()
    ]),

    styles: {
      fontSize: 8,
      cellPadding: 3
    },

    headStyles: {
      fillColor: [0, 153, 255],
      textColor: 255,
      fontStyle: "bold"
    },

    alternateRowStyles: {
      fillColor: [245, 245, 245]
    }
  });

  const endY = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Sensitive prompt information is masked before report generation.",
    14,
    endY
  );

  doc.setFontSize(10);

  doc.text(
    "Generated by PromptSentinel AI Prompt Security Platform",
    14,
    endY + 7
  );

  doc.save("PromptSentinel_History_Report.pdf");
};