import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateHistoryReport = (user, history) => {
  const doc = new jsPDF();

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(0, 153, 255);
  doc.text("PromptSentinel", 14, 20);

  doc.setFontSize(14);
  doc.setTextColor(80);
  doc.text("Prompt Scan History Report", 14, 30);

  doc.setDrawColor(0, 153, 255);
  doc.line(14, 35, 196, 35);

  // User Information
  doc.setFontSize(15);
  doc.setTextColor(0);

  doc.text("User Information", 14, 48);

  doc.setFontSize(11);

  doc.text(`Name : ${user.fullName}`, 18, 58);
  doc.text(`Email : ${user.email}`, 18, 66);
  doc.text(`Role : ${user.role}`, 18, 74);

  doc.text(
    `Generated : ${new Date().toLocaleString()}`,
    18,
    82
  );

  // Table
  autoTable(doc, {
    startY: 92,

    head: [[
      "Prompt",
      "Threat",
      "Attack Type",
      "Risk",
      "Confidence",
      "Date"
    ]],

    body: history.map(scan => [
      scan.prompt,
      scan.threatLevel,
      scan.attackType,
      `${scan.riskScore}/100`,
      `${scan.confidence}%`,
      new Date(scan.createdAt).toLocaleDateString()
    ]),

    styles: {
      fontSize: 8,
      cellPadding: 3
    },

    headStyles: {
      fillColor: [0, 153, 255],
      textColor: 255,
      fontStyle: "bold"
    },

    alternateRowStyles: {
      fillColor: [245, 245, 245]
    }
  });

  const endY = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Generated by PromptSentinel AI Prompt Security Platform",
    14,
    endY
  );

  doc.save("PromptSentinel_History_Report.pdf");
};