import { jsPDF } from "jspdf";

function getThreatColor(level) {
  switch (level) {
    case "LOW":
      return [34, 197, 94];

    case "MEDIUM":
      return [234, 179, 8];

    case "HIGH":
      return [249, 115, 22];

    case "CRITICAL":
      return [239, 68, 68];

    default:
      return [6, 182, 212];
  }
}

export function generateSecurityReport(result) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  const color = getThreatColor(result.threatLevel);

  const reportId =
    "PS-" +
    Math.random().toString(36).substring(2, 8).toUpperCase();

  // ===========================
  // Header
  // ===========================

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);

  doc.text("PromptSentinel", 20, 18);

  doc.setFontSize(11);

  doc.text("AI Prompt Security Platform", 20, 27);

  // ===========================
  // Report Info
  // ===========================

  doc.setTextColor(0, 0, 0);

  doc.setFontSize(18);

  doc.text("AI Security Scan Report", 20, 50);

  doc.setFontSize(11);

  doc.text(
    `Generated : ${new Date().toLocaleString()}`,
    20,
    60
  );

  doc.text(`Report ID : ${reportId}`, 20, 67);

  // ===========================
  // Threat Level
  // ===========================

  doc.setFontSize(15);

  doc.text("Threat Level", 20, 85);

  doc.setTextColor(...color);

  doc.setFont("helvetica", "bold");

  doc.text(result.threatLevel, 70, 85);

  doc.setTextColor(0, 0, 0);

  // ===========================
  // Attack Type
  // ===========================

  doc.setFont("helvetica", "bold");

  doc.text("Attack Type", 20, 98);

  doc.setFont("helvetica", "normal");

  doc.text(result.attackType, 70, 98);

  // ===========================
  // Risk
  // ===========================

  doc.setFont("helvetica", "bold");

  doc.text("Risk Score", 20, 112);

  doc.setFont("helvetica", "normal");

  doc.text(`${result.riskScore}/100`, 70, 112);

  // ===========================
  // Confidence
  // ===========================

  doc.setFont("helvetica", "bold");

  doc.text("Confidence", 20, 125);

  doc.setFont("helvetica", "normal");

  doc.text(`${result.confidence}%`, 70, 125);

  // ===========================
  // Matched Keywords
  // ===========================

  doc.setFont("helvetica", "bold");

  doc.text("Matched Keywords", 20, 142);

  doc.setFont("helvetica", "normal");

  let y = 152;

  if (
    result.matchedPatterns &&
    result.matchedPatterns.length > 0
  ) {
    result.matchedPatterns.forEach((keyword) => {
      doc.text(`• ${keyword}`, 25, y);
      y += 8;
    });
  } else {
    doc.text("No suspicious keywords detected.", 25, y);
    y += 8;
  }

  // ===========================
  // Detection Reason
  // ===========================

  y += 8;

  doc.setFont("helvetica", "bold");

  doc.text("Detection Reason", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");

  const reason = doc.splitTextToSize(
    result.detectionReason,
    165
  );

  doc.text(reason, 20, y);

  y += reason.length * 7 + 10;

  // ===========================
  // Recommendation
  // ===========================

  doc.setFont("helvetica", "bold");

  doc.text("Recommendation", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");

  const recommendation = doc.splitTextToSize(
    result.recommendation,
    165
  );

  doc.text(recommendation, 20, y);

  // ===========================
  // Footer
  // ===========================

  doc.setDrawColor(200);

  doc.line(
    20,
    280,
    pageWidth - 20,
    280
  );

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text(
    "Generated by PromptSentinel AI Prompt Security Platform",
    pageWidth / 2,
    288,
    {
      align: "center",
    }
  );

  doc.save(
    `PromptSentinel_Report_${reportId}.pdf`
  );
}