import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDF = (user, stats, history) => {
  const doc = new jsPDF();

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(0, 153, 255);
  doc.text("PromptSentinel", 14, 20);

  doc.setFontSize(14);
  doc.setTextColor(80);
  doc.text("AI Prompt Security Dashboard Report", 14, 30);

  // Report Info
  doc.setDrawColor(0, 153, 255);
  doc.line(14, 35, 196, 35);

  doc.setFontSize(11);
  doc.setTextColor(40);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    14,
    44
  );

  // User Section
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("User Information", 14, 58);

  doc.setFontSize(12);

  doc.text(`Name : ${user.fullName}`, 18, 68);
  doc.text(`Email : ${user.email}`, 18, 76);
  doc.text(`Role : ${user.role}`, 18, 84);

  // Statistics
  doc.setFontSize(16);
  doc.text("Security Statistics", 14, 100);

  doc.setFontSize(12);

  doc.text(`Total Scans : ${stats.totalScans}`, 18, 110);
  doc.text(`Safe Prompts : ${stats.safePrompts}`, 18, 118);
  doc.text(`High Risk Prompts : ${stats.highRiskPrompts}`, 18, 126);
  doc.text(`Threats Blocked : ${stats.threatsBlocked}`, 18, 134);

  // Security Summary
  let summary =
    "Excellent";

  if (stats.highRiskPrompts > 5)
    summary = "Warning";

  if (stats.highRiskPrompts > 10)
    summary = "Critical";

  doc.setFontSize(16);
  doc.text("Security Summary", 14, 150);

  doc.setFontSize(12);

  doc.text(
    `Overall Security Status : ${summary}`,
    18,
    160
  );

  // Table
  autoTable(doc, {
    startY: 170,

    head: [
      [
        "Prompt",
        "Threat",
        "Attack",
        "Risk",
        "Confidence",
      ],
    ],

    body: history.map((scan) => [
      scan.prompt,
      scan.threatLevel,
      scan.attackType,
      `${scan.riskScore}/100`,
      `${scan.confidence}%`,
    ]),

    styles: {
      fontSize: 9,
      cellPadding: 3,
    },

    headStyles: {
      fillColor: [0, 153, 255],
    },

    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
  });

  const finalY =
    doc.lastAutoTable.finalY + 15;

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text(
    "Generated by PromptSentinel AI Security Platform",
    14,
    finalY
  );

  doc.save("PromptSentinel_Dashboard_Report.pdf");
};