import {
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  AlertTriangle,
  Search,
  Brain,
  Lightbulb,
  Target,
  Download,
  Activity,
  Sparkles,
  ScanSearch,
} from "lucide-react";

import { generateSecurityReport } from "../utils/pdf/generateSecurityReport";

function ResultCard({ result }) {
  if (!result) return null;

  /* =========================================================
     SECURITY STATUS
  ========================================================== */

  const getStatus = () => {
    switch (result.threatLevel) {
      case "SAFE":
        return {
          color: "text-green-400",
          bg: "bg-green-500/10",
          border: "border-green-500/30",
          badgeBg: "bg-green-500/15",
          icon: <ShieldCheck size={58} />,
          description: "No significant security threats were detected.",
          label: "Safe",
        };

      case "LOW":
        return {
          color: "text-lime-400",
          bg: "bg-lime-500/10",
          border: "border-lime-500/30",
          badgeBg: "bg-lime-500/15",
          icon: <ShieldCheck size={58} />,
          description: "The prompt contains minor security indicators.",
          label: "Low Risk",
        };

      case "MEDIUM":
        return {
          color: "text-yellow-400",
          bg: "bg-yellow-500/10",
          border: "border-yellow-500/30",
          badgeBg: "bg-yellow-500/15",
          icon: <AlertTriangle size={58} />,
          description:
            "The prompt contains suspicious security indicators that require attention.",
          label: "Medium Risk",
        };

      case "HIGH":
        return {
          color: "text-orange-400",
          bg: "bg-orange-500/10",
          border: "border-orange-500/30",
          badgeBg: "bg-orange-500/15",
          icon: <ShieldAlert size={58} />,
          description:
            "The prompt contains strong indicators of a potential AI security attack.",
          label: "High Risk",
        };

      case "CRITICAL":
        return {
          color: "text-red-500",
          bg: "bg-red-500/10",
          border: "border-red-500/30",
          badgeBg: "bg-red-500/15",
          icon: <ShieldX size={58} />,
          description:
            "Critical security indicators were detected. Immediate blocking is recommended.",
          label: "Critical Risk",
        };

      default:
        return {
          color: "text-cyan-400",
          bg: "bg-cyan-500/10",
          border: "border-cyan-500/30",
          badgeBg: "bg-cyan-500/15",
          icon: <ShieldCheck size={58} />,
          description: "Security analysis completed.",
          label: "Analyzed",
        };
    }
  };

  const status = getStatus();

  /* =========================================================
     AI ANALYSIS STATUS
  ========================================================== */

  const aiAnalysisActive =
    result.aiAnalysis?.available === true;

  const aiProvider =
    result.aiAnalysis?.provider ||
    "Groq";

  const analysisEngine = aiAnalysisActive
    ? {
        label: `${aiProvider} AI + Local Analysis`,
        description:
          "This result was generated using both the local security engine and Groq AI security analysis.",
        color: "text-green-400",
        bg: "bg-green-500/10",
        border: "border-green-500/30",
        status: "Active",
      }
    : {
        label: "Local Security Analysis",
        description:
          "AI analysis was unavailable or did not return a result. This report was generated by the local security engine.",
        color: "text-yellow-400",
        bg: "bg-yellow-500/10",
        border: "border-yellow-500/30",
        status: "Fallback Mode",
      };

  /* =========================================================
     RESULT DATA
  ========================================================== */

  const riskScore =
    Number(result.riskScore || 0);

  const confidence =
    Number(result.confidence || 0);

  const attackTypes =
    result.attackType
      ? result.attackType
          .split(",")
          .map((item) => item.trim())
          .filter(Boolean)
      : [];

  const matchedPatterns =
    Array.isArray(result.matchedPatterns)
      ? [...new Set(result.matchedPatterns)]
      : [];

  const aiDetectedKeywords =
    Array.isArray(
      result.aiAnalysis?.matchedKeywords
    )
      ? [
          ...new Set(
            result.aiAnalysis.matchedKeywords
          ),
        ]
      : Array.isArray(
          result.matchedKeywords
        )
      ? [
          ...new Set(
            result.matchedKeywords
          ),
        ]
      : [];

  const detectionReason =
    result.detectionReason ||
    "The security engine analyzed the prompt and identified the indicators shown above.";

  const recommendation =
    result.recommendation ||
    "Review the prompt carefully before allowing it to reach an AI model.";

  const aiRecommendation =
    result.aiAnalysis?.recommendation ||
    result.aiRecommendation ||
    "No additional AI recommendation available.";

  const scannedPrompt =
    result.prompt ||
    result.scannedPrompt ||
    "";

  /* =========================================================
     COMPONENT
  ========================================================== */

  return (
    <div
      className={`mt-8 rounded-3xl border p-6 md:p-8 shadow-2xl ${status.bg} ${status.border}`}
    >

      {/* =====================================================
          SECTION 1 — SECURITY REPORT
      ====================================================== */}

      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6 mb-8">

        <div className="flex items-start gap-5">

          <div
            className={`${status.color} shrink-0 mt-1`}
          >
            {status.icon}
          </div>

          <div>

            {/* TITLE + ENGINE STATUS */}

            <div className="flex items-center gap-3 flex-wrap">

              <h2 className="text-3xl md:text-4xl font-bold text-white">
                AI Security Report
              </h2>

              <div
                className={`flex items-center gap-2 ${analysisEngine.bg} border ${analysisEngine.border} px-3 py-1.5 rounded-full`}
              >
                <Activity
                  size={16}
                  className={analysisEngine.color}
                />

                <span
                  className={`${analysisEngine.color} text-xs md:text-sm font-semibold`}
                >
                  {analysisEngine.label}
                </span>

              </div>

            </div>

            {/* THREAT LEVEL */}

            <div className="flex items-center gap-3 mt-4 flex-wrap">

              <p
                className={`text-2xl font-bold ${status.color}`}
              >
                {result.threatLevel || "UNKNOWN"}
              </p>

              <span
                className={`${status.badgeBg} ${status.color} px-3 py-1 rounded-full text-xs font-semibold border ${status.border}`}
              >
                {status.label}
              </span>

            </div>

            {/* SECURITY DESCRIPTION */}

            <p className="text-slate-300 mt-3 max-w-3xl leading-7">
              {status.description}
            </p>

            {/* ENGINE STATUS */}

            <div className="mt-4 flex items-start gap-3">

              <Activity
                size={17}
                className={`${analysisEngine.color} mt-1 shrink-0`}
              />

              <div>

                <p className="text-sm font-semibold text-slate-300">

                  Analysis Engine Status:{" "}

                  <span
                    className={analysisEngine.color}
                  >
                    {analysisEngine.status}
                  </span>

                </p>

                <p className="text-xs text-slate-500 mt-1 max-w-2xl leading-6">
                  {analysisEngine.description}
                </p>

              </div>

            </div>

          </div>

        </div>

      </div>

      {/* =====================================================
          MAIN INFORMATION CARDS
      ====================================================== */}

      <div className="grid md:grid-cols-2 gap-6">

        {/* =================================================
            SECTION 2 — ATTACK TYPE
        ================================================= */}

        <div className="bg-slate-900/90 border border-slate-700/50 rounded-2xl p-6">

          <div className="flex items-center gap-3 mb-4">

            <Target
              className="text-cyan-400"
              size={24}
            />

            <h3 className="font-bold text-lg text-white">
              Attack Type
            </h3>

          </div>

          <p className="text-slate-300 leading-7">
            {result.attackType || "Safe Prompt"}
          </p>

          {attackTypes.length > 0 && (

            <div className="flex flex-wrap gap-2 mt-4">

              {attackTypes.map(
                (type, index) => (

                  <span
                    key={`${type}-${index}`}
                    className="bg-orange-500/10 border border-orange-500/20 text-orange-300 px-3 py-1.5 rounded-full text-xs font-medium"
                  >
                    {type}
                  </span>

                )
              )}

            </div>

          )}

        </div>


        {/* =================================================
            SECTION 3 — RISK SCORE
        ================================================= */}

        <div className="bg-slate-900/90 border border-slate-700/50 rounded-2xl p-6">

          <div className="flex items-center justify-between mb-4">

            <div className="flex items-center gap-3">

              <ShieldAlert
                className="text-orange-400"
                size={24}
              />

              <h3 className="font-bold text-lg text-white">
                Risk Score
              </h3>

            </div>

            <span className="text-xl font-bold text-white">
              {riskScore}/100
            </span>

          </div>

          <div className="w-full bg-slate-700 rounded-full h-4 overflow-hidden">

            <div
              className={`h-4 rounded-full transition-all duration-700 ${
                riskScore >= 80
                  ? "bg-red-500"
                  : riskScore >= 50
                  ? "bg-yellow-400"
                  : "bg-green-400"
              }`}
              style={{
                width: `${Math.min(
                  Math.max(
                    riskScore,
                    0
                  ),
                  100
                )}%`,
              }}
            />

          </div>

          <div className="flex justify-between text-xs text-slate-500 mt-3">

            <span>Low</span>

            <span>Medium</span>

            <span>High</span>

            <span>Critical</span>

          </div>

        </div>


        {/* =================================================
            SECTION 4 — DETECTION CONFIDENCE
        ================================================= */}

        <div className="bg-slate-900/90 border border-slate-700/50 rounded-2xl p-6">

          <div className="flex items-center justify-between mb-4">

            <div className="flex items-center gap-3">

              <Brain
                className="text-cyan-400"
                size={24}
              />

              <h3 className="font-bold text-lg text-white">
                Detection Confidence
              </h3>

            </div>

            <span className="text-xl font-bold text-white">
              {confidence}%
            </span>

          </div>

          <div className="w-full bg-slate-700 rounded-full h-4 overflow-hidden">

            <div
              className="bg-cyan-400 h-4 rounded-full transition-all duration-700"
              style={{
                width: `${Math.min(
                  Math.max(
                    confidence,
                    0
                  ),
                  100
                )}%`,
              }}
            />

          </div>

          <p className="text-xs text-slate-500 mt-3">
            Confidence in the final security classification.
          </p>

        </div>


        {/* =================================================
            SECTION 5 — DETECTION ENGINE
        ================================================= */}

        <div className="bg-slate-900/90 border border-slate-700/50 rounded-2xl p-6">

          <div className="flex items-center gap-3 mb-5">

            <Sparkles
              className="text-violet-400"
              size={24}
            />

            <h3 className="font-bold text-lg text-white">
              Detection Engine
            </h3>

          </div>

          <div className="space-y-4">

            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Local Security Engine
              </span>

              <span className="text-green-400 font-semibold">
                Active
              </span>

            </div>


            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Threat Classification
              </span>

              <span className="text-green-400 font-semibold">
                Active
              </span>

            </div>


            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                AI Analysis
              </span>

              <span
                className={`font-semibold ${
                  aiAnalysisActive
                    ? "text-green-400"
                    : "text-yellow-400"
                }`}
              >
                {aiAnalysisActive
                  ? "Active"
                  : "Unavailable"}
              </span>

            </div>

          </div>

        </div>


        {/* =================================================
            SECTION 6 — MATCHED SECURITY INDICATORS
        ================================================= */}

        <div className="bg-slate-900/90 border border-slate-700/50 rounded-2xl p-6 md:col-span-2">

          <div className="flex items-center gap-3 mb-2">

            <Search
              className="text-green-400"
              size={24}
            />

            <div>

              <h3 className="font-bold text-lg text-white">
                Matched Security Indicators
              </h3>

              <p className="text-sm text-slate-500">
                Patterns and keywords identified during analysis
              </p>

            </div>

          </div>

          {matchedPatterns.length > 0 ? (

            <div className="flex flex-wrap gap-2 mt-5">

              {matchedPatterns.map(
                (pattern, index) => (

                  <span
                    key={`${pattern}-${index}`}
                    className="bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 px-3 py-2 rounded-full text-sm"
                  >
                    {pattern}
                  </span>

                )
              )}

            </div>

          ) : (

            <p className="text-slate-400 mt-4">
              No suspicious security indicators detected.
            </p>

          )}

        </div>


        {/* =================================================
            SECTION 7 — GROQ AI DETECTED KEYWORDS
        ================================================= */}

        <div className="bg-slate-900/90 border border-slate-700/50 rounded-2xl p-6 md:col-span-2">

          <div className="flex items-center gap-3 mb-2">

            <Brain
              className="text-violet-400"
              size={24}
            />

            <div>

              <h3 className="font-bold text-lg text-white">
                Groq AI-Detected Keywords
              </h3>

              <p className="text-sm text-slate-500">
                Additional indicators identified by Groq AI security analysis
              </p>

            </div>

          </div>

          {aiDetectedKeywords.length > 0 ? (

            <div className="flex flex-wrap gap-2 mt-5">

              {aiDetectedKeywords.map(
                (keyword, index) => (

                  <span
                    key={`${keyword}-${index}`}
                    className="bg-violet-500/10 border border-violet-500/20 text-violet-300 px-3 py-2 rounded-full text-sm"
                  >
                    {keyword}
                  </span>

                )
              )}

            </div>

          ) : (

            <p className="text-slate-400 mt-4">
              No additional AI-detected keywords.
            </p>

          )}

        </div>


        {/* =================================================
            SECTION 8 — DETECTION REASON
        ================================================= */}

        <div className="bg-slate-900/90 border border-slate-700/50 rounded-2xl p-6 md:col-span-2">

          <div className="flex items-center gap-3 mb-3">

            <Brain
              className="text-yellow-400"
              size={24}
            />

            <h3 className="font-bold text-lg text-white">
              Detection Reason
            </h3>

          </div>

          <p className="leading-7 text-slate-300">
            {detectionReason}
          </p>

        </div>


        {/* =================================================
            SECTION 9 — SECURITY RECOMMENDATION
        ================================================= */}

        <div className="bg-slate-900/90 border border-slate-700/50 rounded-2xl p-6 md:col-span-2">

          <div className="flex items-center gap-3 mb-3">

            <Lightbulb
              className="text-green-400"
              size={24}
            />

            <div>

              <h3 className="font-bold text-lg text-white">
                Security Recommendation
              </h3>

              <p className="text-sm text-slate-500">
                Final recommendation from PromptSentinel
              </p>

            </div>

          </div>

          <p className="leading-7 text-slate-300">
            {recommendation}
          </p>

        </div>


        {/* =================================================
            SECTION 10 — GROQ AI RECOMMENDATION
        ================================================= */}

        <div className="bg-slate-900/90 border border-cyan-500/10 rounded-2xl p-6 md:col-span-2">

          <div className="flex items-center gap-3 mb-3">

            <Sparkles
              className="text-cyan-400"
              size={24}
            />

            <div>

              <h3 className="font-bold text-lg text-white">
                Groq AI Recommendation
              </h3>

              <p className="text-sm text-slate-500">
                Additional recommendation generated by Groq AI security analysis
              </p>

            </div>

          </div>

          <p className="leading-7 text-slate-300">
            {aiRecommendation}
          </p>

        </div>


        {/* =================================================
            SECTION 11 — SCANNED PROMPT
        ================================================= */}

        <div className="bg-slate-950 border border-slate-700/50 rounded-2xl p-6 md:col-span-2">

          <div className="flex items-center gap-3 mb-4">

            <ScanSearch
              className="text-slate-300"
              size={24}
            />

            <h3 className="font-bold text-lg text-white">
              Scanned Prompt
            </h3>

          </div>

          <div className="bg-slate-900 border border-slate-700 rounded-xl p-5">

            <p className="text-slate-300 leading-7 whitespace-pre-wrap break-words">
              {scannedPrompt ||
                "Prompt text unavailable."}
            </p>

          </div>

        </div>

      </div>


      {/* =====================================================
          DOWNLOAD REPORT
      ====================================================== */}

      <div className="mt-8 flex justify-end">

        <button
          onClick={() =>
            generateSecurityReport(result)
          }
          className="flex items-center gap-3 bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold px-6 py-4 rounded-2xl transition-all duration-200 hover:shadow-lg hover:shadow-cyan-500/20"
        >

          <Download size={22} />

          Download Security Report

        </button>

      </div>

    </div>
  );
}

export default ResultCard;